@echo off
REM ============================================================================
REM  dev.bat — the local development entry point for Motorsport Legends
REM
REM  One place that answers "how do I actually run this?". That question is the
REM  one no repository answers reliably, and it is asked by every new
REM  contributor and by every AI assistant that touches this project. Answering
REM  it once, here, is why AGENTS.md points at this file instead of listing
REM  commands that drift out of date.
REM
REM  Usage:
REM    dev.bat            check the toolchain, install, verify, then run
REM    dev.bat setup      check the toolchain and install dependencies
REM    dev.bat check      everything that must pass before opening a PR
REM    dev.bat test       the test suite only
REM    dev.bat run        start the application locally
REM    dev.bat audit      the deterministic checks this project ships
REM    dev.bat help       this message
REM
REM  Generated by the AI-SDLC starter kit. Edit freely — it is yours now.
REM
REM  Keep this file's line endings as CRLF. cmd.exe parses an LF-only batch file
REM  by eating the first character of every line, which fails in a way that
REM  gives no hint as to the cause. .gitattributes pins this with
REM  `*.bat text eol=crlf`.
REM ============================================================================

setlocal enabledelayedexpansion
cd /d "%~dp0"

REM  Was this double-clicked from Explorer? If so the window closes the instant
REM  we exit and takes the error message with it, so hold it open on the way out.
REM  Explorer launches us as `cmd /c ""C:\path\dev.bat" "` — note the doubled
REM  quote after /c, which an ordinary `cmd /c "dev.bat check"` from a script or
REM  a pipeline does not have, so neither gets a prompt it cannot answer.
REM  Quotes are swapped for a sentinel first: %cmdcmdline% contains quotes of
REM  its own, and comparing it raw makes cmd choke on the `if` line itself.
REM  Set DEV_NO_PAUSE to suppress the hold outright.
set "_cl=%cmdcmdline:"=@%"
set "_hold="
if not "!_cl!"=="!_cl:/c @@=!" set "_hold=1"
if defined DEV_NO_PAUSE set "_hold="

if /i "%~1"=="help"  goto :help
if /i "%~1"=="-h"    goto :help
if /i "%~1"=="setup" goto :setup_cmd
if /i "%~1"=="check" goto :check_cmd
if /i "%~1"=="test"  goto :test_cmd
if /i "%~1"=="lint"  goto :lint_cmd
if /i "%~1"=="build" goto :build_cmd
if /i "%~1"=="run"   goto :run_cmd
if /i "%~1"=="audit" goto :audit_cmd
if not "%~1"=="" goto :unknown

REM --- default: the whole loop, in the order that fails fastest ---------------
REM  Want the dev server without waiting on lint and a production build?
REM  `dev.bat run`.
call :setup || goto :fail
call :check || goto :fail
call :run
goto :done

REM  Single-command entry points. Each one has to route its subroutine's exit
REM  code into the script's own, or `dev.bat check` reports success to a
REM  pipeline no matter what the linter said.
:setup_cmd
call :setup || goto :fail
goto :done
:check_cmd
call :check || goto :fail
goto :done
:test_cmd
call :test || goto :fail
goto :done
:lint_cmd
call :lint || goto :fail
goto :done
:build_cmd
call :build || goto :fail
goto :done
:run_cmd
call :run || goto :fail
goto :done
:audit_cmd
call :audit || goto :fail
goto :done

REM ---------------------------------------------------------------------------
REM  Every npm invocation goes through here. Two things this fixes, both of
REM  which broke the default flow outright:
REM
REM  `pushd`/`popd` rather than `cd`, because a bare `cd app` outlives the
REM  subroutine it sits in. Once :setup had done it, :lint's own `cd app` was
REM  looking for app\app, failed, short-circuited the `&&` so the linter never
REM  ran at all, and left errorlevel 1 behind — which read as a lint failure.
REM
REM  `call npm`, because npm on Windows is npm.cmd. Starting one batch file
REM  from another without `call` transfers control instead of nesting it: npm
REM  runs, and every line after it in the caller is silently abandoned.
:npm
pushd app || (
  echo   Cannot find the app\ directory next to this script.
  exit /b 1
)
call npm %*
set "_rc=!errorlevel!"
popd
exit /b !_rc!

REM ---------------------------------------------------------------------------
:setup
echo.
echo == Toolchain ==
node --version
if errorlevel 1 (
  echo   Node.js was not found on PATH. Install it, then run this again.
  exit /b 1
)

echo.
echo == Environment ==
if not exist ".env" (
  if exist ".env.example" (
    copy /y ".env.example" ".env" >nul
    echo   Created .env from .env.example. Fill in the real values before running.
  ) else (
    echo   No .env found and no .env.example to copy from.
  )
) else (
  echo   .env present.
)

echo.
echo == Install ==
call :npm install
if errorlevel 1 exit /b 1
exit /b 0

REM ---------------------------------------------------------------------------
REM  Everything that must be green before a pull request. Ordered cheapest and
REM  most-likely-to-fail first, the same principle the pipeline uses — being
REM  told about a lint error after a twelve minute test run is a design defect.
:check
call :lint || exit /b 1
call :test || exit /b 1
call :build || exit /b 1
echo.
echo   All checks passed.
exit /b 0

REM ---------------------------------------------------------------------------
:lint
echo.
echo == Lint ==
call :npm run lint --if-present
if errorlevel 1 exit /b 1
exit /b 0

REM ---------------------------------------------------------------------------
REM  This project has no test runner yet, which AGENTS.md says out loud. It
REM  warns rather than fails: a hard failure here made `dev.bat` unusable as a
REM  way to start the app, which is the one thing every contributor needs from
REM  it. Wire up a runner and make this a real gate.
:test
echo.
echo == Tests ==
echo   TODO^(setup^): no test runner is configured, so `dev.bat check` is not
echo   checking any behaviour. Skipping.
exit /b 0

REM ---------------------------------------------------------------------------
:build
echo.
echo == Build ==
call :npm run build --if-present
if errorlevel 1 exit /b 1
exit /b 0

REM ---------------------------------------------------------------------------
:run
echo.
echo == Run ==
call :npm run dev
exit /b !errorlevel!

REM ---------------------------------------------------------------------------
REM  The deterministic checks. Not part of `check` because they inform a human
REM  decision rather than gating one — see docs/cicd/pipeline-notes.md.
:audit
echo.
echo == Documentation drift ==
node tools/doc-drift.mjs
echo.
echo == Release risk ==
node tools/release-risk.mjs
exit /b 0

REM ---------------------------------------------------------------------------
:help
echo.
echo   dev.bat            check the toolchain, install, verify, then run
echo   dev.bat setup      check the toolchain and install dependencies
echo   dev.bat check      everything that must pass before opening a PR
echo   dev.bat test       the test suite only
echo   dev.bat lint       the linter only
echo   dev.bat build      the build only
echo   dev.bat run        start the application locally
echo   dev.bat audit      documentation drift and release risk
echo.
goto :done

:unknown
echo   Unknown command: %~1
echo   Try: dev.bat help
if defined _hold pause
endlocal
exit /b 1

:fail
echo.
echo   FAILED. Nothing further was run.
if defined _hold pause
endlocal
exit /b 1

REM  No hold on the way out of a success: there is nothing left to read, and a
REM  `pause` on the happy path is a script that hangs whatever wraps it. The
REM  hold belongs on the two paths that print something worth reading.
:done
endlocal
exit /b 0
