#!/usr/bin/env bash
# =============================================================================
#  dev.sh — the local development entry point for Motorsport Legends
#
#  The POSIX twin of dev.bat. One place that answers "how do I actually run
#  this?" — the question no repository answers reliably, and the one asked by
#  every new contributor and every AI assistant that touches this project.
#  AGENTS.md points here rather than listing commands that drift out of date.
#
#  Usage:
#    ./dev.sh            check the toolchain, install, verify, then run
#    ./dev.sh setup      check the toolchain and install dependencies
#    ./dev.sh check      everything that must pass before opening a PR
#    ./dev.sh test       the test suite only
#    ./dev.sh run        start the application locally
#    ./dev.sh audit      the deterministic checks this project ships
#
#  Generated by the AI-SDLC starter kit. Edit freely — it is yours now.
# =============================================================================

set -euo pipefail
cd "$(dirname "$0")"

step() { printf '\n== %s ==\n' "$1"; }

# Every npm invocation goes through here, in a subshell. A bare `cd app`
# outlives the function it sits in: once setup had done it, lint's own `cd app`
# was looking for app/app, failed, and short-circuited the `&&` so the linter
# never ran. The parentheses confine the directory change to this call.
npm_app() { ( cd app && npm "$@" ); }

setup() {
  step 'Toolchain'
  node --version || { echo '  Node.js was not found on PATH.'; exit 1; }

  step 'Environment'
  if [ ! -f .env ]; then
    if [ -f .env.example ]; then
      cp .env.example .env
      echo '  Created .env from .env.example. Fill in the real values before running.'
    else
      echo '  No .env found and no .env.example to copy from.'
    fi
  else
    echo '  .env present.'
  fi

  step 'Install'
  npm_app install
}

# Everything that must be green before a pull request. Ordered cheapest and
# most-likely-to-fail first, the same principle the pipeline uses — being told
# about a lint error after a twelve minute test run is a design defect.
check() {
  lint
  test_suite
  build
  printf '\n  All checks passed.\n'
}

lint() {
  step 'Lint'
  npm_app run lint --if-present
}

# This project has no test runner yet, which AGENTS.md says out loud. It warns
# rather than fails: a hard failure here made the default flow unusable as a way
# to start the app, which is the one thing every contributor needs from it. Wire
# up a runner and make this a real gate.
test_suite() {
  step 'Tests'
  echo '  TODO(setup): no test runner is configured, so check is not checking any'
  echo '  behaviour. Skipping.'
}

build() {
  step 'Build'
  npm_app run build --if-present
}

run() {
  step 'Run'
  npm_app run dev
}

# Not part of check: these inform a human decision rather than gating one.
# See docs/cicd/pipeline-notes.md.
audit() {
  step 'Documentation drift'
  node tools/doc-drift.mjs
  step 'Release risk'
  node tools/release-risk.mjs
}

case "${1:-}" in
  setup) setup ;;
  check) check ;;
  test)  test_suite ;;
  lint)  lint ;;
  build) build ;;
  run)   run ;;
  audit) audit ;;
  help|-h|--help)
    sed -n '4,19p' "$0" | sed 's/^# \{0,1\}//'
    ;;
  '')
    setup
    check
    run
    ;;
  *)
    echo "  Unknown command: $1"
    echo '  Try: ./dev.sh help'
    exit 1
    ;;
esac
