import type { Section } from '../types'

export const SECTIONS: Section[] = [
  {
    id: 'heritage',
    title: 'GULLWING',
    subtitle: '1954 — Stuttgart',
    copy: 'Some machines are not built. They are summoned. The Mercedes-Benz 300 SL arrived not as an automobile but as a declaration — that speed, beauty, and engineering could occupy the same breath.',
    progressStart: 0,
    progressEnd: 0.13,
  },
  {
    id: 'design',
    title: 'THE FORM',
    subtitle: 'Sculpture in Motion',
    copy: 'Rudolf Uhlenhaut gave the 300 SL a body that the wind itself could not improve. Each pressed-aluminium panel was shaped by hand, fitted by eye, and finished to a standard that left no room for compromise.',
    features: [
      'Hand-formed aluminium coachwork',
      'Space-frame tubular chassis',
      'Reclined seating for aerodynamic profile',
      'Full-width curved windscreen',
    ],
    progressStart: 0.13,
    progressEnd: 0.27,
  },
  {
    id: 'engine',
    title: 'THE ENGINE',
    subtitle: 'Fuel Injection, 1954',
    copy: 'The straight-six at 2996cc was the first production car to employ Bosch mechanical fuel injection — a technology borrowed from aviation. It produced 215 horsepower and pushed the 300 SL beyond 160 miles per hour.',
    stats: [
      { value: '215',  label: 'Horsepower',   unit: 'HP'        },
      { value: '163',  label: 'Top Speed',    unit: 'mph'       },
      { value: '8.8',  label: '0–60 mph',     unit: 'sec'       },
      { value: '2996', label: 'Displacement', unit: 'cc'        },
    ],
    progressStart: 0.27,
    progressEnd: 0.42,
  },
  {
    id: 'doors',
    title: 'THE DOORS',
    subtitle: 'An Audacious Gesture',
    copy: 'The space-frame left no room for conventional doors. The solution — hinged at the roofline, opening to the sky — was not a concession to engineering. It was an act of theatre.',
    features: [
      'Roof-hinged butterfly configuration',
      'Structural integration with space-frame',
      'Interior latch mechanism',
      'Signature silhouette in profile',
    ],
    progressStart: 0.42,
    progressEnd: 0.56,
  },
  {
    id: 'interior',
    title: 'THE COCKPIT',
    subtitle: 'Purpose Over Comfort',
    copy: 'There is no excess here. The driver faces a sparse tableau of gauges, leather, and polished metal. Every element present for a reason. Every absence deliberate.',
    features: [
      'Reclined driver positioning',
      'VDO instrument cluster',
      'Ivory-rimmed steering wheel',
      'Hand-stitched leather throughout',
    ],
    progressStart: 0.56,
    progressEnd: 0.70,
  },
  {
    id: 'legacy',
    title: 'THE LEGACY',
    subtitle: 'Seven Decades',
    copy: 'The 300 SL did not merely win races. It redefined what was possible. Le Mans 1952. The Carrera Panamericana. The Mille Miglia. And beyond the circuits, it occupied the garages of kings, actors, and those who simply understood.',
    stats: [
      { value: '1400', label: 'Gullwings Built',  unit: ''           },
      { value: '1952', label: 'Le Mans Victory',  unit: ''           },
      { value: '70',   label: 'Years of Legend',  unit: 'yrs'        },
      { value: '1',    label: 'Original',         unit: 'of a kind'  },
    ],
    progressStart: 0.70,
    progressEnd: 0.82,
  },
  {
    id: 'stars',
    title: 'THE REGISTER',
    subtitle: 'Those Who Understood',
    copy: 'The 300 SL did not seek famous owners. It attracted them.',
    progressStart: 0.82,
    progressEnd: 0.91,
  },
  {
    id: 'acquire',
    title: 'ACQUIRE',
    subtitle: 'Own a Legend',
    copy: 'Reserved for those who understand that a motor car can be a work of art. Each example presented is subject to full provenance research, concours preparation, and discreet private negotiation.',
    progressStart: 0.91,
    progressEnd: 1.00,
  },
]

export const TOTAL_SCROLL_HEIGHT = '2000vh'
