#!/usr/bin/env bash
# =============================================================================
#  dev.sh — the local development entry point for {{project.name}}
#
#  The POSIX twin of dev.bat. One place that answers "how do I actually run
#  this?" — the question no repository answers reliably, and the one asked by
#  every new contributor and every AI assistant that touches this project.
#  AGENTS.md points here rather than listing commands that drift out of date.
#
#  Usage:
#    ./dev.sh            check the toolchain, install, verify, then run
#    ./dev.sh setup      check the toolchain and install dependencies
#    ./dev.sh check      everything that must pass before opening a PR
#    ./dev.sh test       the test suite only
#    ./dev.sh run        start the application locally
#    ./dev.sh audit      the deterministic checks this project ships
#
#  Generated by the AI-SDLC starter kit. Edit freely — it is yours now.
# =============================================================================

set -euo pipefail
cd "$(dirname "$0")"

step() { printf '\n== %s ==\n' "$1"; }

setup() {
  step 'Toolchain'
{{#if project.hasToolCheck}}
  {{project.toolCheck}} || { echo '  Required toolchain not found on PATH.'; exit 1; }
{{/if}}
{{#unless project.hasToolCheck}}
  echo '  TODO(setup): add the version check for this project'"'"'s toolchain.'
{{/unless}}
{{#if answers.usesDocker}}
  docker --version >/dev/null 2>&1 || { echo '  Docker is required but was not found.'; exit 1; }
{{/if}}
{{#if answers.envExample}}

  step 'Environment'
  if [ ! -f .env ]; then
    if [ -f .env.example ]; then
      cp .env.example .env
      echo '  Created .env from .env.example. Fill in the real values before running.'
    else
      echo '  No .env found and no .env.example to copy from.'
    fi
  else
    echo '  .env present.'
  fi
{{/if}}

  step 'Install'
{{#if project.hasInstallCommand}}
  {{project.installCommand}}
{{/if}}
{{#unless project.hasInstallCommand}}
  echo '  TODO(setup): add the dependency install command.'
{{/unless}}
{{#if answers.usesDocker}}

  step 'Local services'
  docker compose up -d
{{/if}}
}

# Everything that must be green before a pull request. Ordered cheapest and
# most-likely-to-fail first, the same principle the pipeline uses — being told
# about a lint error after a twelve minute test run is a design defect.
check() {
{{#if project.hasLintCommand}}
  lint
{{/if}}
  test_suite
{{#if project.hasBuildCommand}}
  build
{{/if}}
  printf '\n  All checks passed.\n'
}

lint() {
{{#if project.hasLintCommand}}
  step 'Lint'
  {{project.lintCommand}}
{{/if}}
  :
}

test_suite() {
  step 'Tests'
{{#if project.hasTestCommand}}
  {{project.testCommand}}
{{/if}}
{{#unless project.hasTestCommand}}
  echo '  TODO(setup): add the test command. Until this line is real, check is checking nothing.'
  exit 1
{{/unless}}
}

build() {
{{#if project.hasBuildCommand}}
  step 'Build'
  {{project.buildCommand}}
{{/if}}
  :
}

run() {
  step 'Run'
{{#if project.hasRunCommand}}
  {{project.runCommand}}
{{/if}}
{{#unless project.hasRunCommand}}
  echo '  TODO(setup): add the command that starts this application locally.'
{{/unless}}
}

# Not part of check: these inform a human decision rather than gating one.
# See docs/cicd/pipeline-notes.md.
audit() {
{{#if answers.installDocDrift}}
  step 'Documentation drift'
  node tools/doc-drift.mjs
{{/if}}
{{#if answers.installRiskCheck}}
  step 'Release risk'
  node tools/release-risk.mjs
{{/if}}
{{#unless answers.anyTooling}}
  echo '  No deterministic checks are installed. Re-run the setup wizard to add them.'
{{/unless}}
}

case "${1:-}" in
  setup) setup ;;
  check) check ;;
  test)  test_suite ;;
  lint)  lint ;;
  build) build ;;
  run)   run ;;
  audit) audit ;;
  help|-h|--help)
    sed -n '4,19p' "$0" | sed 's/^# \{0,1\}//'
    ;;
  '')
    setup
    check
    run
    ;;
  *)
    echo "  Unknown command: $1"
    echo '  Try: ./dev.sh help'
    exit 1
    ;;
esac
