@echo off
REM ============================================================================
REM  dev.bat — the local development entry point for {{project.name}}
REM
REM  One place that answers "how do I actually run this?". That question is the
REM  one no repository answers reliably, and it is asked by every new
REM  contributor and by every AI assistant that touches this project. Answering
REM  it once, here, is why AGENTS.md points at this file instead of listing
REM  commands that drift out of date.
REM
REM  Usage:
REM    dev.bat            check the toolchain, install, verify, then run
REM    dev.bat setup      check the toolchain and install dependencies
REM    dev.bat check      everything that must pass before opening a PR
REM    dev.bat test       the test suite only
REM    dev.bat run        start the application locally
REM    dev.bat audit      the deterministic checks this project ships
REM    dev.bat help       this message
REM
REM  Generated by the AI-SDLC starter kit. Edit freely — it is yours now.
REM
REM  Keep this file's line endings as CRLF. cmd.exe parses an LF-only batch file
REM  by eating the first character of every line, which fails in a way that
REM  gives no hint as to the cause. If your repository normalises line endings,
REM  add `*.bat text eol=crlf` to .gitattributes.
REM ============================================================================

setlocal enabledelayedexpansion
cd /d "%~dp0"

if /i "%~1"=="help"  goto :help
if /i "%~1"=="-h"    goto :help
if /i "%~1"=="setup" goto :setup
if /i "%~1"=="check" goto :check
if /i "%~1"=="test"  goto :test
if /i "%~1"=="lint"  goto :lint
if /i "%~1"=="build" goto :build
if /i "%~1"=="run"   goto :run
if /i "%~1"=="audit" goto :audit
if not "%~1"=="" goto :unknown

REM --- default: the whole loop, in the order that fails fastest ---------------
call :setup || goto :fail
call :check || goto :fail
call :run
goto :done

REM ---------------------------------------------------------------------------
:setup
echo.
echo == Toolchain ==
{{#if project.hasToolCheck}}
call {{project.toolCheck}}
if errorlevel 1 (
  echo   Required toolchain not found on PATH. Install it, then run this again.
  exit /b 1
)
{{/if}}
{{#unless project.hasToolCheck}}
echo   TODO^(setup^): add the version check for this project's toolchain.
{{/unless}}
{{#if answers.usesDocker}}
docker --version >nul 2>nul
if errorlevel 1 (
  echo   Docker is required for local dependencies but was not found on PATH.
  exit /b 1
)
{{/if}}
{{#if answers.envExample}}

echo.
echo == Environment ==
if not exist ".env" (
  if exist ".env.example" (
    copy /y ".env.example" ".env" >nul
    echo   Created .env from .env.example. Fill in the real values before running.
  ) else (
    echo   No .env found and no .env.example to copy from.
  )
) else (
  echo   .env present.
)
{{/if}}

echo.
echo == Install ==
{{#if project.hasInstallCommand}}
call {{project.installCommand}}
if errorlevel 1 exit /b 1
{{/if}}
{{#unless project.hasInstallCommand}}
echo   TODO^(setup^): add the dependency install command.
{{/unless}}
{{#if answers.usesDocker}}

echo.
echo == Local services ==
call docker compose up -d
if errorlevel 1 exit /b 1
{{/if}}
exit /b 0

REM ---------------------------------------------------------------------------
REM  Everything that must be green before a pull request. Ordered cheapest and
REM  most-likely-to-fail first, the same principle the pipeline uses — being
REM  told about a lint error after a twelve minute test run is a design defect.
:check
{{#if project.hasLintCommand}}
call :lint || exit /b 1
{{/if}}
call :test || exit /b 1
{{#if project.hasBuildCommand}}
call :build || exit /b 1
{{/if}}
echo.
echo   All checks passed.
exit /b 0

REM ---------------------------------------------------------------------------
:lint
{{#if project.hasLintCommand}}
echo.
echo == Lint ==
call {{project.lintCommand}}
if errorlevel 1 exit /b 1
{{/if}}
exit /b 0

REM ---------------------------------------------------------------------------
:test
echo.
echo == Tests ==
{{#if project.hasTestCommand}}
call {{project.testCommand}}
if errorlevel 1 exit /b 1
{{/if}}
{{#unless project.hasTestCommand}}
echo   TODO^(setup^): add the test command. Until this line is real, `dev.bat check`
echo   is not checking anything.
exit /b 1
{{/unless}}
exit /b 0

REM ---------------------------------------------------------------------------
:build
{{#if project.hasBuildCommand}}
echo.
echo == Build ==
call {{project.buildCommand}}
if errorlevel 1 exit /b 1
{{/if}}
exit /b 0

REM ---------------------------------------------------------------------------
:run
echo.
echo == Run ==
{{#if project.hasRunCommand}}
call {{project.runCommand}}
{{/if}}
{{#unless project.hasRunCommand}}
echo   TODO^(setup^): add the command that starts this application locally.
{{/unless}}
exit /b 0

REM ---------------------------------------------------------------------------
REM  The deterministic checks. Not part of `check` because they inform a human
REM  decision rather than gating one — see docs/cicd/pipeline-notes.md.
:audit
{{#if answers.installDocDrift}}
echo.
echo == Documentation drift ==
call node tools/doc-drift.mjs
{{/if}}
{{#if answers.installRiskCheck}}
echo.
echo == Release risk ==
call node tools/release-risk.mjs
{{/if}}
{{#unless answers.anyTooling}}
echo   No deterministic checks are installed. Re-run the setup wizard to add them.
{{/unless}}
exit /b 0

REM ---------------------------------------------------------------------------
:help
echo.
echo   dev.bat            check the toolchain, install, verify, then run
echo   dev.bat setup      check the toolchain and install dependencies
echo   dev.bat check      everything that must pass before opening a PR
echo   dev.bat test       the test suite only
echo   dev.bat lint       the linter only
echo   dev.bat build      the build only
echo   dev.bat run        start the application locally
echo   dev.bat audit      documentation drift and release risk
echo.
goto :done

:unknown
echo   Unknown command: %~1
echo   Try: dev.bat help
exit /b 1

:fail
echo.
echo   FAILED. Nothing further was run.
exit /b 1

:done
endlocal
